### ISSUE TITLE
If 4-8-8 is used to do QAT, how to process weight in inference?

### ISSUE THREAD

**Issue by jackzhou121** [facebookresearch/LLM-QAT#10]
4-8-8 is used in my job, so In inference, should I use int 8 weight and int 8 input in nn.Linear() or convert both to fp16 and then do nn.Linear()? if you provide an example for inference, that's realy make sense for us

**Comment by Luoqiu76** [comment]
May I ask how it is resolved? Do we need to use other packages, such as bitsandbytes, to quantify the weight after training is completed?
