### ISSUE TITLE
How should I save the 8 bit model？

### ISSUE THREAD

**Issue by liguodongiot** [facebookresearch/LLM-QAT#11]
When I run to the script `bash run_train.sh 8 8 8`， the ouput weight is always BF16。

I understand the output weights should be saved as int8.

I hope to get your answer。

  Thanks!

**Comment by liuzechun** [comment]
Hi, Thanks for your interest in our work! Because it is fake quantization so the weights are still stored in BF16. In the forward pass, it will be converted to INT8 in the quantization function.

**Comment by Luoqiu76** [comment]
So how do we use the quantified weights for interfacing? For example, if we have already obtained the weights through training, do we need other packages or implement them ourselves to complete the quantization operation, rather than a fake quantization node
