### ISSUE TITLE
The choice of kd_loss_scale

### ISSUE THREAD

**Issue by zhanlaoban** [facebookresearch/LLM-QAT#13]
Hello Doc Liu, thank you for your inspiring work in the QAT domain.
I have a question regarding the choice of [kd_loss_scale.](https://github.com/facebookresearch/LLM-QAT/blob/f4d873a501845cc4133d5398a9c8203c53eec2c9/utils/kd_trainer.py#L79) Can you provide your recommended settings for optimization? Your guidance is immensely valuable to me.

**Comment by liuzechun** [comment]
Hi, Thanks for your question and nice words. We just simply use kd_loss_scale = 1.0 since we don't use any other losses such as label_loss.
