### ISSUE TITLE
Is there an efficient way to generate data?

### ISSUE THREAD

**Issue by benyang0506** [facebookresearch/LLM-QAT#14]
Hello, I'm trying to run the data generation. But the data generation is particularly slow right now. Is there an efficient way to generate data?
Thanks!

**Comment by wejoncy** [comment]
Move `model` and `input` to GPU will imrpove it dramaticlly

**Comment by benyang0506** [comment]
Thank you for your answer! I noticed that you used 64 gpu to generate data, I wonder how long it took.

**Comment by liuzechun** [comment]
Updated the code. It takes approximately 1 day to generate 100k sentences.
