### ISSUE TITLE
no smoothquant in QuantizeLinear

### ISSUE THREAD

**Issue by priscilla-pan** [facebookresearch/LLM-QAT#15]
no smoothquant attr in QuantizeLinear.  which cause error when  run ./run_train.sh 4 8 4.  

what kind of GPU you use in training?  A100 40G or 80G

**Comment by zhanlaoban** [comment]
Just remove smoothquant attr in QuantizeLinear, which works for me.

**Comment by priscilla-pan** [comment]
i've removed it already.  just tell them.

The problem is cuda out  of memory when  use 5 A100 40G GPUs.

what about you?

**Comment by 1963306815** [comment]
Yes. My problem is the same when using 8 A800 80G GPUs. Maybe the smoothquant can reduce the usage of the GPU's memory.

**Comment by priscilla-pan** [comment]
> Yes. My problem is the same when using 8 A800 80G GPUs. Maybe the smoothquant can reduce the usage of the GPU's memory.

set gradient_checkpointing to True works for me

**Comment by liuzechun** [comment]
Thanks for letting us know! Updated the code to resolve these issues.
