### ISSUE TITLE
Harcoded train paths and configuration for table in readme 

### ISSUE THREAD

**Issue by aitorormazabal** [facebookresearch/LLM-QAT#3]
Hello,

I am trying to run the code in this repository, but it seems that with the provided code as-is the `train_data_local_path` and `eval_data_local_path` arguments in `run_train.sh` are ignored by `train.py,` and instead hardcoded datasets are used (wikitext). Additionally, `use_kd` is set to False in `run_train.sh`, although the paper seems to use KD for the main results. Were the numbers in the readme obtained with this codebase, and if so would it be possible to clarify what configuration was used to do so?

**Comment by liuzechun** [comment]
Thanks for reporting this bug. Yes, we used KD for the experiments. We have fixed both!
