### ISSUE TITLE
No randomization operation for the first token in data generation phrase. 

### ISSUE THREAD

**Issue by xingyueye** [facebookresearch/LLM-QAT#9]
As stated in the title, the code is as follows:
https://github.com/facebookresearch/LLM-QAT/blob/cfd70ffe0dd7e35c47832d19302c12892702bdd1/generate_data.py#L36C1-L37C1

**Comment by liuzechun** [comment]
Yes, we are actually traverse 32000 tokens to ensure the coverage different data distributions.
